# Generated by Django 2.0.6 on 2018-09-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('except_catcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exceptionreport',
            options={'ordering': ['-id']},
        ),
    ]
